### ISSUE TITLE
Automatically use number of virtual CPUs as default for number of threads 

### ISSUE THREAD

**Issue by torfmaster** [torfmaster/ribzip2#1]
Currently, the number of CPU defaults to 1 if it is not provided. As compression profits significantly from multi-threading it would make sense to use the `num_cpus` crate to use a higher default for the number of CPUs.

**Comment by hemantku** [comment]
Hi @torfmaster I would be interested on working on this issue. I have done some fair bit of rust coding recently. Wondering if I can help out?

**Comment by torfmaster** [comment]
Ah, it has already closed through #15 but this hasn't been handled by github. If you want to you can take a look into #3, for example. It looks involved but the actually doing should be rather quick and easy.

**Comment by torfmaster** [comment]
Closed via #15
