### ISSUE TITLE
Check formatting of rust files in CI

### ISSUE THREAD

**Issue by torfmaster** [torfmaster/ribzip2#11]
Check that all files in the workspace are formatted properly using `rustfmt --check` and fail the CI otherwise. As an extra the following could be improved w.r.t. to formatting

 * add a vscode workspace file which recommends the rust analyzer plugin
 * set "format on save" as default setting

**Comment by RishiKumarRay** [comment]
How to add this ? add a vscode workspace file  any references

**Comment by RishiKumarRay** [comment]
ok added this extension , now how to add format option?

**Comment by torfmaster** [comment]
Hi, thank you for taking this issue! You can add a `settings` field to the workspace file containing `"editor.formatOnSave": true`.

**Comment by RishiKumarRay** [comment]
Where can i find workspace file?

**Comment by torfmaster** [comment]
There is currently no workspace file, yet. You would need to create one.

**Comment by DipayanP007** [comment]
Hey @torfmaster I raised a PR for this. kindly check it

**Comment by torfmaster** [comment]
Closed through PR #13
