### ISSUE TITLE
Improve CLI ergonomy

### ISSUE THREAD

**Issue by torfmaster** [torfmaster/ribzip2#5]
Improve ergonomy of CLI
- [ ] use bzip2 logic of compression/uncompression by decompression a file named `x.y.bz2` to `x.y` and compressing `x.y` to `x.y.bz2`
- [ ] check whether output file exists and fail with an error message
- [ ] handle I/O failures with meaningful error messages

**Comment by caglaryucekaya** [comment]
Hi I'd like to take this

**Comment by torfmaster** [comment]
Okay, have fun! If you have questions, just ask!

**Comment by caglaryucekaya** [comment]
Can you explain the first item a little bit further? I'm not sure if I understand it correctly

**Comment by torfmaster** [comment]
Clear: if you have an output file `bla.ext` then the compressed file should be written to `bla.ext.bz2` upon compression. If the latter exists, compression should be aborted with a meaningful error message. Likewise upon decompression `bla.ext.bz2` should be written to `bla.ext`.
I would recommend that neither of the input files gets deleted upon success, but that's kind of up to you.

**Comment by torfmaster** [comment]
This is now closed.
